
CREATE DATABASE TPCDS;
CREATE OR REPLACE SCHEMA RAW; 

create or replace TABLE TPCDS.RAW.INVENTORY (
	INV_DATE_SK NUMBER(38,0) NOT NULL,
	INV_ITEM_SK NUMBER(38,0) NOT NULL,
	INV_QUANTITY_ON_HAND NUMBER(38,0) NOT NULL,
	INV_WAREHOUSE_SK NUMBER(38,0)
);
